//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssimilationSoftware.MediaSync.Core.Properties {
    
    
    internal sealed partial class Settings {
        
        private static Settings defaultInstance = new Settings();
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }

        private string _mediaSyncConnectionString;
        public string MediaSyncConnectionString {
            get {
                return _mediaSyncConnectionString;
            }
        }

        private bool _configured;
        public bool Configured {
            get {
                return _configured;
            }
            set {
                _configured = value;
            }
        }

        private string _metaDataFolder;
        public string MetadataFolder {
            get {
                return _metaDataFolder;
            }
            set {
                _metaDataFolder = value;
            }
        }

        private string _machineName;
        public string MachineName {
            get {
                return _machineName;
            }
            set {
                _machineName = value;
            }
        }
    }
}
